"""add_gcn_spatial_layer_types

Revision ID: 45ce553d0710
Revises: 6a7baea82d03
Create Date: 2025-11-11 17:01:03.756657

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45ce553d0710"
down_revision: str | Sequence[str] | None = "6a7baea82d03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="nrf_reference",
        enum_name="spatial_layer_type",
        new_values=[
            "WWTW_CATCHMENTS",
            "LPA_BOUNDARIES",
            "NN_CATCHMENTS",
            "SUBCATCHMENTS",
            "GCN_RISK_ZONES",
            "GCN_PONDS",
            "EDP_EDGES",
        ],
        affected_columns=[
            TableReference(
                table_schema="nrf_reference",
                table_name="spatial_layer",
                column_name="layer_type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="nrf_reference",
        enum_name="spatial_layer_type",
        new_values=[
            "WWTW_CATCHMENTS",
            "LPA_BOUNDARIES",
            "NN_CATCHMENTS",
            "SUBCATCHMENTS",
        ],
        affected_columns=[
            TableReference(
                table_schema="nrf_reference",
                table_name="spatial_layer",
                column_name="layer_type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
