"""initial version

Revision ID: 6a7baea82d03
Revises:
Create Date: 2025-10-22 14:03:14.822204

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a7baea82d03"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NOW = sa.text("now()")


def upgrade() -> None:
    """Upgrade schema."""
    # Create nrf_reference schema
    op.execute("CREATE SCHEMA IF NOT EXISTS nrf_reference")

    # Enable PostGIS extension
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "WWTW_CATCHMENTS",
        "LPA_BOUNDARIES",
        "NN_CATCHMENTS",
        "SUBCATCHMENTS",
        name="spatial_layer_type",
        schema="nrf_reference",
    ).create(op.get_bind())
    op.create_table(
        "coefficient_layer",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=27700,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("crome_id", sa.String(), nullable=True),
        sa.Column("land_use_cat", sa.String(), nullable=True),
        sa.Column("nn_catchment", sa.String(), nullable=True),
        sa.Column("subcatchment", sa.String(), nullable=True),
        sa.Column("lu_curr_n_coeff", sa.Float(), nullable=True),
        sa.Column("lu_curr_p_coeff", sa.Float(), nullable=True),
        sa.Column("n_resi_coeff", sa.Float(), nullable=True),
        sa.Column("p_resi_coeff", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=NOW,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nrf_reference",
    )
    # Note: idx_coefficient_layer_geometry is automatically created by GeoAlchemy2's spatial_index=True
    op.create_index(
        op.f("ix_nrf_reference_coefficient_layer_crome_id"),
        "coefficient_layer",
        ["crome_id"],
        unique=False,
        schema="nrf_reference",
    )
    op.create_index(
        op.f("ix_nrf_reference_coefficient_layer_nn_catchment"),
        "coefficient_layer",
        ["nn_catchment"],
        unique=False,
        schema="nrf_reference",
    )
    op.create_index(
        op.f("ix_nrf_reference_coefficient_layer_subcatchment"),
        "coefficient_layer",
        ["subcatchment"],
        unique=False,
        schema="nrf_reference",
    )
    op.create_index(
        op.f("ix_nrf_reference_coefficient_layer_version"),
        "coefficient_layer",
        ["version"],
        unique=False,
        schema="nrf_reference",
    )
    op.create_table(
        "lookup_table",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=NOW,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_lookup_name_version"),
        schema="nrf_reference",
    )
    op.create_index(
        op.f("ix_nrf_reference_lookup_table_name"),
        "lookup_table",
        ["name"],
        unique=False,
        schema="nrf_reference",
    )
    op.create_index(
        op.f("ix_nrf_reference_lookup_table_version"),
        "lookup_table",
        ["version"],
        unique=False,
        schema="nrf_reference",
    )
    op.create_table(
        "spatial_layer",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "layer_type",
            postgresql.ENUM(
                "WWTW_CATCHMENTS",
                "LPA_BOUNDARIES",
                "NN_CATCHMENTS",
                "SUBCATCHMENTS",
                name="spatial_layer_type",
                schema="nrf_reference",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=27700,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=NOW,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nrf_reference",
    )
    # Note: idx_spatial_layer_geometry is automatically created by GeoAlchemy2's spatial_index=True
    op.create_index(
        op.f("ix_nrf_reference_spatial_layer_layer_type"),
        "spatial_layer",
        ["layer_type"],
        unique=False,
        schema="nrf_reference",
    )
    op.create_index(
        op.f("ix_nrf_reference_spatial_layer_name"),
        "spatial_layer",
        ["name"],
        unique=False,
        schema="nrf_reference",
    )
    op.create_index(
        op.f("ix_nrf_reference_spatial_layer_version"),
        "spatial_layer",
        ["version"],
        unique=False,
        schema="nrf_reference",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_nrf_reference_spatial_layer_version"),
        table_name="spatial_layer",
        schema="nrf_reference",
    )
    op.drop_index(
        op.f("ix_nrf_reference_spatial_layer_name"),
        table_name="spatial_layer",
        schema="nrf_reference",
    )
    op.drop_index(
        op.f("ix_nrf_reference_spatial_layer_layer_type"),
        table_name="spatial_layer",
        schema="nrf_reference",
    )
    # Note: idx_spatial_layer_geometry is automatically dropped by GeoAlchemy2 when table is dropped
    op.drop_table("spatial_layer", schema="nrf_reference")
    op.drop_index(
        op.f("ix_nrf_reference_lookup_table_version"),
        table_name="lookup_table",
        schema="nrf_reference",
    )
    op.drop_index(
        op.f("ix_nrf_reference_lookup_table_name"),
        table_name="lookup_table",
        schema="nrf_reference",
    )
    op.drop_table("lookup_table", schema="nrf_reference")
    op.drop_index(
        op.f("ix_nrf_reference_coefficient_layer_version"),
        table_name="coefficient_layer",
        schema="nrf_reference",
    )
    op.drop_index(
        op.f("ix_nrf_reference_coefficient_layer_subcatchment"),
        table_name="coefficient_layer",
        schema="nrf_reference",
    )
    op.drop_index(
        op.f("ix_nrf_reference_coefficient_layer_nn_catchment"),
        table_name="coefficient_layer",
        schema="nrf_reference",
    )
    op.drop_index(
        op.f("ix_nrf_reference_coefficient_layer_crome_id"),
        table_name="coefficient_layer",
        schema="nrf_reference",
    )
    # Note: idx_coefficient_layer_geometry is automatically dropped by GeoAlchemy2 when table is dropped
    op.drop_table("coefficient_layer", schema="nrf_reference")
    sa.Enum(
        "WWTW_CATCHMENTS",
        "LPA_BOUNDARIES",
        "NN_CATCHMENTS",
        "SUBCATCHMENTS",
        name="spatial_layer_type",
        schema="nrf_reference",
    ).drop(op.get_bind())
    # ### end Alembic commands ###

    # Drop schema (cascade will remove any remaining objects)
    op.execute("DROP SCHEMA IF EXISTS nrf_reference CASCADE")
